[package]
name = "dart-yrs-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dart-sys = "4.0.2"
yrs = "0.16.3"

[lib]
crate-type = ["cdylib"]
